<?php
/**
 * AppsApi
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\UserRatingsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User ratings API docs
 *
 * To access the API: 1. Register a client with the proper permissions (`user-ratings-api.*`) in the [Softonic OAuth Admin](https://oauth-admin.softonic.com) 1. Retrieve a token for that client with the proper scopes from the [Softonic OAuth API](https://oauth-v2.softonic.com). 1. Copy the token in the input field at the top of the page
 *
 * OpenAPI spec version: 1.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\UserRatingsApiSdk\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Softonic\UserRatingsApiSdk\ApiException;
use Softonic\UserRatingsApiSdk\Configuration;
use Softonic\UserRatingsApiSdk\HeaderSelector;
use Softonic\UserRatingsApiSdk\ObjectSerializer;

/**
 * AppsApi Class Doc Comment
 *
 * @category Class
 * @package  Softonic\UserRatingsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAppUserRating
     *
     * Register a rating for the given app
     *
     * @param  string $app_id App id (required)
     * @param  \Softonic\UserRatingsApiSdk\Client\Model\AppUserRating $app_user_rating app_user_rating (optional)
     *
     * @throws \Softonic\UserRatingsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function createAppUserRating($app_id, $app_user_rating = null)
    {
        $this->createAppUserRatingWithHttpInfo($app_id, $app_user_rating);
    }

    /**
     * Operation createAppUserRatingWithHttpInfo
     *
     * Register a rating for the given app
     *
     * @param  string $app_id App id (required)
     * @param  \Softonic\UserRatingsApiSdk\Client\Model\AppUserRating $app_user_rating (optional)
     *
     * @throws \Softonic\UserRatingsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAppUserRatingWithHttpInfo($app_id, $app_user_rating = null)
    {
        $returnType = '';
        $request = $this->createAppUserRatingRequest($app_id, $app_user_rating);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation createAppUserRatingAsync
     *
     * Register a rating for the given app
     *
     * @param  string $app_id App id (required)
     * @param  \Softonic\UserRatingsApiSdk\Client\Model\AppUserRating $app_user_rating (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAppUserRatingAsync($app_id, $app_user_rating = null)
    {
        return $this->createAppUserRatingAsyncWithHttpInfo($app_id, $app_user_rating)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAppUserRatingAsyncWithHttpInfo
     *
     * Register a rating for the given app
     *
     * @param  string $app_id App id (required)
     * @param  \Softonic\UserRatingsApiSdk\Client\Model\AppUserRating $app_user_rating (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAppUserRatingAsyncWithHttpInfo($app_id, $app_user_rating = null)
    {
        $returnType = '';
        $request = $this->createAppUserRatingRequest($app_id, $app_user_rating);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAppUserRating'
     *
     * @param  string $app_id App id (required)
     * @param  \Softonic\UserRatingsApiSdk\Client\Model\AppUserRating $app_user_rating (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createAppUserRatingRequest($app_id, $app_user_rating = null)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling createAppUserRating'
            );
        }

        $resourcePath = '/apps/{appId}/user-ratings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($app_id !== null) {
            $resourcePath = str_replace(
                '{' . 'appId' . '}',
                ObjectSerializer::toPathValue($app_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($app_user_rating)) {
            $_tempBody = $app_user_rating;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAppUserRatings
     *
     * Get the rating information about the given app
     *
     * @param  string $app_id App id (required)
     *
     * @throws \Softonic\UserRatingsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getAppUserRatings($app_id)
    {
        $this->getAppUserRatingsWithHttpInfo($app_id);
    }

    /**
     * Operation getAppUserRatingsWithHttpInfo
     *
     * Get the rating information about the given app
     *
     * @param  string $app_id App id (required)
     *
     * @throws \Softonic\UserRatingsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAppUserRatingsWithHttpInfo($app_id)
    {
        $returnType = '';
        $request = $this->getAppUserRatingsRequest($app_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation getAppUserRatingsAsync
     *
     * Get the rating information about the given app
     *
     * @param  string $app_id App id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAppUserRatingsAsync($app_id)
    {
        return $this->getAppUserRatingsAsyncWithHttpInfo($app_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAppUserRatingsAsyncWithHttpInfo
     *
     * Get the rating information about the given app
     *
     * @param  string $app_id App id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAppUserRatingsAsyncWithHttpInfo($app_id)
    {
        $returnType = '';
        $request = $this->getAppUserRatingsRequest($app_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAppUserRatings'
     *
     * @param  string $app_id App id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAppUserRatingsRequest($app_id)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling getAppUserRatings'
            );
        }

        $resourcePath = '/apps/{appId}/user-ratings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($app_id !== null) {
            $resourcePath = str_replace(
                '{' . 'appId' . '}',
                ObjectSerializer::toPathValue($app_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAverageAppUserRatings
     *
     * Get a list of apps with their average user ratings and number of votes
     *
     * @param  \DateTime $updated_after Date to filter the results (optional)
     * @param  string $from_scroll Token to request the next search context (optional)
     * @param  int $scroll_size Number of results per request (default 10) (optional)
     * @param  int $scroll_timeout Timeout to keep the search context open (in seconds) (optional, default to 60)
     *
     * @throws \Softonic\UserRatingsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getAverageAppUserRatings($updated_after = null, $from_scroll = null, $scroll_size = null, $scroll_timeout = '60')
    {
        $this->getAverageAppUserRatingsWithHttpInfo($updated_after, $from_scroll, $scroll_size, $scroll_timeout);
    }

    /**
     * Operation getAverageAppUserRatingsWithHttpInfo
     *
     * Get a list of apps with their average user ratings and number of votes
     *
     * @param  \DateTime $updated_after Date to filter the results (optional)
     * @param  string $from_scroll Token to request the next search context (optional)
     * @param  int $scroll_size Number of results per request (default 10) (optional)
     * @param  int $scroll_timeout Timeout to keep the search context open (in seconds) (optional, default to 60)
     *
     * @throws \Softonic\UserRatingsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAverageAppUserRatingsWithHttpInfo($updated_after = null, $from_scroll = null, $scroll_size = null, $scroll_timeout = '60')
    {
        $returnType = '';
        $request = $this->getAverageAppUserRatingsRequest($updated_after, $from_scroll, $scroll_size, $scroll_timeout);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation getAverageAppUserRatingsAsync
     *
     * Get a list of apps with their average user ratings and number of votes
     *
     * @param  \DateTime $updated_after Date to filter the results (optional)
     * @param  string $from_scroll Token to request the next search context (optional)
     * @param  int $scroll_size Number of results per request (default 10) (optional)
     * @param  int $scroll_timeout Timeout to keep the search context open (in seconds) (optional, default to 60)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAverageAppUserRatingsAsync($updated_after = null, $from_scroll = null, $scroll_size = null, $scroll_timeout = '60')
    {
        return $this->getAverageAppUserRatingsAsyncWithHttpInfo($updated_after, $from_scroll, $scroll_size, $scroll_timeout)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAverageAppUserRatingsAsyncWithHttpInfo
     *
     * Get a list of apps with their average user ratings and number of votes
     *
     * @param  \DateTime $updated_after Date to filter the results (optional)
     * @param  string $from_scroll Token to request the next search context (optional)
     * @param  int $scroll_size Number of results per request (default 10) (optional)
     * @param  int $scroll_timeout Timeout to keep the search context open (in seconds) (optional, default to 60)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAverageAppUserRatingsAsyncWithHttpInfo($updated_after = null, $from_scroll = null, $scroll_size = null, $scroll_timeout = '60')
    {
        $returnType = '';
        $request = $this->getAverageAppUserRatingsRequest($updated_after, $from_scroll, $scroll_size, $scroll_timeout);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAverageAppUserRatings'
     *
     * @param  \DateTime $updated_after Date to filter the results (optional)
     * @param  string $from_scroll Token to request the next search context (optional)
     * @param  int $scroll_size Number of results per request (default 10) (optional)
     * @param  int $scroll_timeout Timeout to keep the search context open (in seconds) (optional, default to 60)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAverageAppUserRatingsRequest($updated_after = null, $from_scroll = null, $scroll_size = null, $scroll_timeout = '60')
    {
        if ($scroll_size !== null && $scroll_size > 10000) {
            throw new \InvalidArgumentException('invalid value for "$scroll_size" when calling AppsApi.getAverageAppUserRatings, must be smaller than or equal to 10000.');
        }
        if ($scroll_size !== null && $scroll_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$scroll_size" when calling AppsApi.getAverageAppUserRatings, must be bigger than or equal to 1.');
        }

        if ($scroll_timeout !== null && $scroll_timeout > 300) {
            throw new \InvalidArgumentException('invalid value for "$scroll_timeout" when calling AppsApi.getAverageAppUserRatings, must be smaller than or equal to 300.');
        }
        if ($scroll_timeout !== null && $scroll_timeout < 1) {
            throw new \InvalidArgumentException('invalid value for "$scroll_timeout" when calling AppsApi.getAverageAppUserRatings, must be bigger than or equal to 1.');
        }


        $resourcePath = '/apps/user-ratings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($updated_after !== null) {
            $queryParams['updatedAfter'] = ObjectSerializer::toQueryValue($updated_after);
        }
        // query params
        if ($from_scroll !== null) {
            $queryParams['fromScroll'] = ObjectSerializer::toQueryValue($from_scroll);
        }
        // query params
        if ($scroll_size !== null) {
            $queryParams['scrollSize'] = ObjectSerializer::toQueryValue($scroll_size);
        }
        // query params
        if ($scroll_timeout !== null) {
            $queryParams['scrollTimeout'] = ObjectSerializer::toQueryValue($scroll_timeout);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
