<?php
/**
 * AppsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\UserRatingsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User ratings API docs
 *
 * To access the API: 1. Register a client with the proper permissions (`user-ratings-api.*`) in the [Softonic OAuth Admin](https://oauth-admin.softonic.com) 1. Retrieve a token for that client with the proper scopes from the [Softonic OAuth API](https://oauth-v2.softonic.com). 1. Copy the token in the input field at the top of the page
 *
 * OpenAPI spec version: 1.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\UserRatingsApiSdk;

use \Softonic\UserRatingsApiSdk\Configuration;
use \Softonic\UserRatingsApiSdk\ApiException;
use \Softonic\UserRatingsApiSdk\ObjectSerializer;

/**
 * AppsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\UserRatingsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAppUserRating
     *
     * Register a rating for the given app.
     *
     */
    public function testCreateAppUserRating()
    {
    }

    /**
     * Test case for getAppUserRatings
     *
     * Get the rating information about the given app.
     *
     */
    public function testGetAppUserRatings()
    {
    }

    /**
     * Test case for getAverageAppUserRatings
     *
     * Get a list of apps with their average user ratings and number of votes.
     *
     */
    public function testGetAverageAppUserRatings()
    {
    }
}
